version: '3.8'
services:
  ### demo service
#  demo-service-dc:
#    build:
  ### database service
  postgres:
    image: postgres
    container_name: "postgres"
    env_file:
      - configuration/environment/postgres.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - "./scripts/create_database.sh:/docker-entrypoint-initdb.d/create_database.sh:ro"